# Generated by Django 3.1 on 2021-08-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('ostan', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('shahr', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200c\u200cها',
            },
        ),
    ]
