# Generated by Django 3.1 on 2021-10-12 11:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_P', models.CharField(max_length=50, verbose_name='عنوان فارسی')),
                ('title_E', models.CharField(max_length=50, verbose_name='عنوان انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'سطح سختی سفر',
                'verbose_name_plural': 'سطح سختی سفر',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_P', models.CharField(max_length=50, verbose_name='عنوان فارسی')),
                ('title_E', models.CharField(max_length=50, verbose_name='عنوان انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'نوع حمل و نقل',
                'verbose_name_plural': 'نوع حمل و نقل',
            },
        ),
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_P', models.CharField(max_length=50, verbose_name='عنوان فارسی')),
                ('title_E', models.CharField(max_length=50, verbose_name='عنوان انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'مدت زمان سفر',
                'verbose_name_plural': 'مدت زمان سفر',
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_P', models.CharField(max_length=50, verbose_name='عنوان فارسی')),
                ('title_E', models.CharField(max_length=50, verbose_name='عنوان انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='ایجاد شده در')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='location.traveltype', verbose_name='دسته\u200cمادر')),
            ],
            options={
                'verbose_name': 'نوع سفر',
                'verbose_name_plural': 'انواع سفر',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='difficulty',
            field=models.ManyToManyField(related_name='loc_difficulty', to='location.Difficulty', verbose_name='درجه سختی'),
        ),
        migrations.AddField(
            model_name='location',
            name='transport_type',
            field=models.ManyToManyField(related_name='loc_transport', to='location.TransportType', verbose_name='نوع حمل و نقل'),
        ),
        migrations.AddField(
            model_name='location',
            name='travel_time',
            field=models.ManyToManyField(related_name='loc_time', to='location.TravelTime', verbose_name='زمانبندی'),
        ),
        migrations.AddField(
            model_name='location',
            name='travel_type',
            field=models.ManyToManyField(related_name='loc_travel', to='location.TravelType', verbose_name='نوع سفر'),
        ),
    ]
