# Generated by Django 3.2.4 on 2021-06-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='users.customuser', verbose_name='کاربر')),
                ('first_name', models.CharField(default='طبیعت\u200cگرد', max_length=40, verbose_name='نام')),
                ('last_name', models.CharField(default='0', max_length=40, verbose_name='نام خانوادگی')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], default='F', max_length=1, verbose_name='جنسیت')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'db_table': 'user_profile',
            },
        ),
    ]
